# Generated by Django 4.1.6 on 2023-02-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cpf_cliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamentos',
            field=models.ManyToManyField(blank=True, null=True, to='clientes.departamento'),
        ),
    ]
